name: test web

on:
  push:
    branches:
      - '**'

jobs:
  test-e2e:
    name: Test Bankguru
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: E2E test
      run: |
        cd cypress
        npm install
        npm run login

